---
title: Курс "Общая экология"
description: Материалы и объявления 
---
 
## О курсе
Не смотря на то, что современная биология у многих ассоциируется с изучением молекулярных основ жизни, одной из центральных тенденций в развитии естествознания, несомненно, является познание организации и функционирования надорганизменных систем, относящихся к области компетенции экологии. В настоящий момент трудно говорить о какой-то единой науке «экологии», под этим термином кроется целый куст дисциплин. Поэтому курс «Общая экология» направлен, в первую очередь, на рассмотрение арсенала подходов, методов и принципов формулировок гипотез при изучении систем, включающих в себя в качестве первичных элементов организмы, популяции, сообщества и среду их существования.

### Цель и задачи курса
Главная цель курса - знакомство студентов не столько с огромным набором фактических данных, накопленных в экологических исследованиях, а, скорее, с методологией экологических исследований. 

**К числу главных задач курса мы относим**    
- Выработку навыков представления изучаемых явлений в системной форме и отражения полученных знаний в форме моделей.     
- Выработку навыков самостоятельного поиска информации, связанной с экологическими исследованиями, и ее критического осмысления.    
- Знакомство с наиболее разработанными обобщениями в области аутэкологии, популяционной биологии и синэкологии.    
- Знакомство с подходами и методами, используемыми в реальных экологических исследованиях.   

## Расписание и контакты

Лекции: с 22 сентября по две пары.
О расписании семинаров объявим дополнительно

Лекторы: 

- Хайтов Вадим Михайлович - polydora[]rambler.ru
- Тиходеева Марина Юрьевна - marinaur[]list.ru 

Инструкторы семинаров:

- Мирин Денис Моисеевич
- Мельницкий Станислав Игоревич
- Чернова Елена Николаевна
- Сафронова Дарья Вячеславовна
- Крапивин Владимир Александрович
- ....



## Структура курса, задания, дедлайны и оценки

Курс состоит из трех частей, реализуемых в два этапа

**Этап 1** (первые 6 недель + 1 в резерве).

1.Лекции   
2.Самостоятельная работа   

**Этап 2** (6 недель после окончания лекций)   
3.Семинары 


**Оценки**   
Политика курса направлена на использование накопительной системы, в которой  дробные оценки накапливаются студентом за все время прохождения курса. Финальная оценка за курс (которая пойдет в зачетку) складывается из нескольких частей.


1.*Оценки за самостоятельную работу*. Эти оценки производятся на основе тестов, которые будут размещены на платформе Stepik. После мягкого дедлайна (1 неделя) за задания начисляется только половина баллов. Студенты, не имеющие возможности использовать сетевые ресурсы, будут проходить тестирование в режиме offline, с использованием индивидуальных бумажных тестов.   

2.*Оценки за контрольные работы*. Всего будет две контрольные работы, которые будут проходить в формате online тестов, которые будут размещены на платформе Stepik. Каждый тест будет открыт для прохождения в определенный, согласованный с курсом, день. Студенты смогут его проходить в любом удобном для них месте, но только в течение 2 часов с момента начала тестирования. Студенты, не имеющие возможности использовать сетевые ресурсы, будут проходить тестирование, с использованием индивидуальных бумажных тестов в аудитории в течение двух часов.   

3.*Оценки за семинары*. По итогам семинаров студенты получат задания, за выполнение которых будет выставлены отдельные оценки. Студенты, активно работающие не семинарах, получают дополнительные баллы на счет за самостоятельные работы.

4.*Устный экзамен*. Экзамен будет проходить в очной форме. Каждый студент получит один вопрос, на который надо дать развернутый ответ. Экзаменатор вправе задавать дополнительные вопросы. Студенты не набравшие баллов, необходимых для оценки «удовлетворительно», за самостоятельную работу, получают дополнительный билет. Аналогично, студенты не набравшие баллов, необходимых для оценки «удовлетворительно», за контрольные работы получают по дополнительному билет. То есть студент не прошедший ни одного теста (или прошедший их плохо) имеет возможность получить хорошую оценку, но при более сложном экзамене (максимальное количество вопросов - 4). Так что лучше работать в течение всего семестра.  


<!-- - [Другие ресурсы и книги для изучения R и статистики](resources.html) -->

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->
