---
title: Лекции и Презентации
---

## Темы лекций

### Тема 1. Краткое введение в общую теорию систем и методологию исследований.
Объект-система:  Первичные элементы, отношения и законы композиции. Что может быть и чего не может быть и что должно быть у любых систем. Способы преобразования систем. Многообразие, как неизбежность представления объектов, как систем. Система объектов. Таксономия и мерономия С. В. Мейена, как превод языка ОТС на биологический язык. Схема исследования любой биологической системы. Модель, как интеллектуальное отражение действительности. Какие бывают модели. Построение модели, как задача исследования. Проблема соотношения модели и наблюдаемых явлений. 

### Тема 2. Живые системы. 
Репликаторы и машины выживания. Два основных свойства живых систем (самовоспроизведение и обмен с окружающей средой). Спектр уровней организации живых систем и область компетенции экологии.  Определения экологии. Место экологии среди других биологических дисциплин.  Разделы экологии: аутэкология, демэкология и синэкология. Кардинальные проблемы, в которых фокусируются основные направления и разделы современной экологии: обзор тематик ведущих журналов, публикующих работы в области экологии (в том числе экологические механизмы адаптации к среде, регуляция численности популяций, управление продукционными процессами, устойчивость природных и антропогенных ценозов, экологическая индикация).


### Тема 3. Организм и среда.

Понятие экологического фактора. Проблема измерение уровня благосостояния организма.  Принцип действия экологического фактора: оптимум, зона нормальной жизнедеятельности, пределы выносливости. Закон толерантности Шелфорда.  Экотипы и физиологические расы, связь с эволюционным процессом. Эврибионты и стенобионты. Изменение реакции организмов на действие экологического фактора в пространстве и времени. Фотопериодические реакции. Ритмы в активности организмов: Циркадные и лунные ритмы. Совместное действие нескольких факторов. Реакция организмов на одновременное действие нескольких факторов: ведущие и лимитируемые факторы. Правило Либиха. Среда и действие факторов среды. Среды жизни. 


### Тема 4. Классификации экологических факторов. 
Общие принципы построения классификаций с точки зрения ОТС. Зачем нужны классификации. Традиционные классификации: абиотические и биотические факторы; биогенные и абиогенные факторы; факторы, зависящие и не зависящие от плотности популяции.Факторы витальные и сигнальные. Витальное действие температуры, пищи, хищников и паразитов. Экологическое действие света и температуры. Правило суммы эффективных температур. Классификация А.С. Мончадского: первичные периодические, вторичные периодические и непериодические факторы. Специфика действия непериодических факторов. Экологической ниша, первое знакомство: многомерная модель Хатчинсона. Ресурсы и ох отличие от других факторов среды.

### Тема 5. Уровни действия абиотических факторов. 
Уровень особей: поведенческие реакции и физиологическая перестройка организма. Понятие адаптивного явления. Популяционный уровень: адаптивная эволюция и пространственное распределение. Принципы зональной и вертикальной смены стаций. Суточная смена стаций. Видовой уровень. Роль максимальных и минимальных температур в географическом распространении видов. Географическая изменчивость видов: правило Бергмана, Аллена и Глогера. Специфика действия факторов на уровне экологических систем. Обобщающая схема действия абиотических факторов на различных уровнях организации.


### Тема 6. Популяция с точки зрения эколога. 
Проблема определения популяции. Типы популяционных группировок: популяции, гемипопуляции, микропопуляции, микрогемипопуляции, поселения. 


### Тема 7. Структура популяции. 
Пространственная структура популяционных группировок. Половая структура популяций. Определение пола у разных организмов.  Аномалии в половой структуре. Циклические изменения в половой структуре. Генетическая структура популяций. Возрастная структура популяции: проблема определения возраста, кривые выживания, аномалии в возрастной структуре.      


### Тема 8. Динамика численности популяции. 
Основное уравнение динамики численности. Рождаемость, смертность, эмиграция, иммиграция. Удельная рождаемость и удельная смертность. Мальтузианский параметр. Экспоненциальная модель роста численности популяции. Законы в экологии Закон неограниченного роста численности. Представление модели неограниченного роста в дифференциальной и рекуррентной форме. Модели ограниченного роста. Понятие емкости среды. Равновесные и оппортунистические популяции. Характерные признаки r- и K-отбора. Решения дифференциального уравнения, описывающего ограниченный рост численности. Логистическая кривая. Модель хаотического колебания численности, как одно из решений дифференциального уравнения. Динамика первого и второго порядка. Три типа зависимости роста популяции от ее плотности.Модели динамики численности второго порядка. Примеры динамики второго порядка среди организмов (насекомые, грызуны, хищные млекопитающие, моллюски-фильтраторы).Факторы динамики численности: модифицирующие и регулирующие.  Причины долговременных колебаний в численности популяций человека. Модель секулярных циклов. 

### Тема 9.  Взаимоотношения организмов. 
Классификация взаимоотношений по природе элементов системы: Внутривидовые взаимоотношения (гомотипические реакции), межвидовые взаимоотношения (геторотипические реакции). Классификация взаимоотношеий по формату среды реализации отношений: только среда первого порядка (несимбиотические отношения) , среда первого и воторого порядка (симбиотические отношения). Несимбиотические отношения: Нейтрализм, протокооперация и смежные явления, гнездовой паразитизм и смежные явления, аменсализм и смежные явления, синойкия и смежные явления.        

### Тема 10. Несимбиотические взаимоотношения потребителя и био-ресурса (трофическе связи).
Пары терминов: продуцент и консумент, автотроф и гетеротроф. Пища как ресурс. Световое питание растений. Минеральное питание растений. Факторы, лимитирующие питание растений. Биоэлементы, основные элементы минерального питания и микроэлементы. Особенности действия пищи как экологического фактора в питании животных. Пищевые режимы и пищевая специализация животных. Питание детритофагов. Механизмы пищевого предпочтения у животных-зоофагов и животных-фитофагов. Типы питания животных. Классификация «жнецов» и «охотников» по формам питания. Различия между тремя экологическими группами фитофагов: моно-, олиго- и полифагами. Сублетальное хищничество. Модели динамики численности популяций потребителя (хищника) и биоресурса (жертвы).Функциональная реакция хищников-полифагов и численная реакция хищников-олигофагов. 

### Тема 11. Конкурентные отношения. 
Ресурсы и их влияние на организм. Гомотипические реакции: эффект группы, эффект массы, внутривидовая конкуренция. Эффект Олли. Две формы конкуренции: прямая и косвенная. Явление территориальности. Теоря агрессии К.Лоренца. Межвидовая конкуренция Модели динамики численности популяций конкурирующих видов. Принцип конкурентного исключения. Экологическая ниша второе знакомство: пространственная ниша, трофическая ниша. Фундаментальная и реализованная экологические ниши. Лицензионная модель экологической ниши. Экологическая диверсификация. Смещение признаков – одно из следствий экологической диверсификации. Причины и последствия расхождения ниш. Факторы, определяющие успех конкурентной борьбы. Влияние межвидовой и внутривидовой конкуренции на место видов в экосистеме. 

### Тема 12. Симбиозы.
Трудности в определений. Среда первого и второго порядка. Три формы симбиозов (комменсализм, мутуализм и паразитизм). Эволюционные пути появления симбиозов. Паразитические формы среди разных организмов. Формы влияния паразита на хозяина (физиологические, этологические и экологическе модификации). Могут ли паразиты оказывать положительное влияние? Формы влияния хозяина на паразитов (иммунитет, поведенческие защитные реакции). Популяционные эффекты от влияния паразитов (влияние на репродуктивные процессы в популяции хозяина, изменения половой структуры популяции). Жизненные циклы паразитов с точки зрения экологии. 


### Тема 13. Экологическая система. 

Концепция экосистемы. Автотрофный и гетеротрофный компоненты экосистемы, их пространственное и временнóе разделение. Сопоставление понятий «экосистема» и «биогеоценоз». Структура биогеоценоза по Сукачеву. Структура экосистемы: продуценты, консументы, редуценты, поток энергии и два круговорота веществ. Разнообразие экосистем. Гомеостаз экосистемы, его механизмы. 
Тема 10. Энергетика экосистемы. Поток энергии в экосистеме. Дыхание сообщества как способ поддержания высокой степени внутренней упорядоченности. Мера термодинамической упорядоченности и принцип стабильности. Этапы продуцирования органического вещества в экосистеме: первичная продукция (валовая и чистая), вторичная продукция, чистая продукция сообщества. Блочная модель экосистемы с разделением потока энергии на W и R. Формула урожая и корни противоречий между хозяйственными устремлениями человека и стратегией развития природы. Баланс между валовой первичной продукцией и дыханием сообщества. Пищевые цепи и пищевые сети. Поток энергии, проходящий через последовательные трофические уровни. Универсальная модель потока энергии; ее использование в экологии. Построение сетевой диаграммы пищевой сети экосистемы пресноводного водоема. Три группы экологических эффективностей. Отношение продукции к биомассе данного и соседнего трофических уровней. Зависимость биомассы и продукции от размера особей. Трофическая структура экосистемы. Распределение числа особей, биомассы и энергии по трофическим уровням: основные обобщения. Примеры пирамид чисел, биомассы и энергии.

### Тема 14. Биогеохимические циклы. 
Обменный и резервный фонды биогеохимических циклов. Основные пути поступления веществ в обменный фонд. Блочная модель круговорота, его основные компоненты. Относительная скорость движения веществ в экосистеме. Процесс эвтрофирования пресноводных экосистем. Пример цикла с резервным фондом в атмосфере (цикл азота). Пример цикла с резервным фондом в земной коре (цикл фосфора). Пример цикла с резервным фондом в земной коре и атмосфере (цикл серы). Принципиальная схема движения веществ в обменном фонде.


### Тема 15. Биотическое сообщество. 
Анализ биотического сообщества. Разделение понятий: состав (видовое разнообразие, состав по жизненным формам, возрастной состав популяций), строение (вертикальное и горизонтальное) и структура (консорции и ценоэлементы) биотического сообщества. Концепция экологического доминирования. Степень доминантности и показатель доминирования. Классификация видов по их влиянию на свойства сообщества. Общая зависимость между числом видов и числом особей, приходящихся на один вид. Индекс (показатель) видового разнообразия. Закономерности видового разнообразия (зависимость видового разнообразия от продуктивности экосистемы, стрессовых воздействий и др.). Проблемы сохранения биоразнообразия. Внутренняя организация биотического сообщества: характер стратификации, зональности, активности, пищевых связей, групповых отношений и др. Стохастические связи.


### Тема 16. Развитие и эволюция экосистемы. 
Аллогенные и автогенные изменения экосистем. Признаки развития экосистемы, их динамика в процессе сукцессии. Автотрофная и гетеротрофная сукцессии. Биоэнергетика развития экосистемы. Изменения в характере пищевых цепей, замыкание биогеохимических циклов. Увеличение числа видов – основа для развития гетеротипических реакций. Общая стратегия экологической сукцессии. Примеры первичной и вторичной сукцессий. Понятие серий и климакса. Антропогенный субклимакс. Нарушения и катастрофы. Циклический характер сукцессий. Эволюция экосистем. Коэволюция и групповой отбор. Отражение эволюции в сукцессии. Сбалансированность экосистемы и темпы эволюции организмов. Понятие экологического кризиса. Массовые вымирания: ордовикско-силурское, девонское, пермское, триасосвое, мел-палеогеновое и их причины.

### Тема 17. Экосистемы как хорологические единицы биосферы. 
Принципы разграничения биогеоценозов. Выбор характерных признаков. Роль экологических индикаторов в процедуре разграничения экосистем. Экотон и краевой эффект. Свойства континуума и дискретности биогеоценозов.  Экологические шкалы. Биомы – основные наземные экосистемы. Экологические эквиваленты. Экосистемы суши и океана. Биосфера, ее строение и характерные признаки. Распределение живых организмов в литосфере, атмосфере и гидросфере. Парабиосферные области, эоловая зона. Лимитирующие факторы и первичная продукция биосферы. 

<!-- Концепция ноосферы. -->



## Презентации
Презентации будут открываться по мере прохождения тем.




